---
title: "Data and Approaches"
output: html_document
---


<style type="text/css">

body{ /* Normal  */
      font-size: 16px;
  }
}
h1.title {
  font-size: 30px;
  color: DarkBlue;
}
h1 { /* Header 1 */
  font-size: 28px;
  color: DarkBlue;
}
h2 { /* Header 2 */
    font-size: 16px;
  color: DarkBlue;
}

}
code.r{ /* Code block */
    font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 14px;
}
</style>


\


# Data

## Source
We used database "Airline On-Time Performance Data" coming from Bureau of Transportation Statistics (BTS), which has records of the on-time performance of domestic flights operated by large air carriers. The database is accessed from [here](https://www.transtats.bts.gov/Fields.asp?Table_ID=236). 

## Overview
We selected 23 out of 109 variables of our interest, and chose time ranges from 2012 Janurary to 2016 December. In total, there are 29722792 observations of 23 variables in our dataset. Each observation represent one flight. Variables fall into three categories based on variable types: _Indicator variables_, _Continuous variables_, _Categorical variables_,  including summary information on the flights performance and descriptive information about flights.

## Definition of flight delay
A flight is counted as "delayed" if it arrived 15min later than schedule arrival. 

## 5 Causes of delay

* Carrier Delay: including Aircraft cleaning, Maintenance, Late crew, _etc._
* Weather Delay: including Below minimum conditions, Thunder Storm, Tornado _etc._
* National Air System Delay (`nas_delay`): including Air Traffic Control (ATC), Bird strikes, Closed Runways _etc._
* Security Delay: including Lines at screening area that exceed standard time, Bomb threat, Inoperative screening equipment - TSA _etc._
* Late Arriving Aircraft Delay (`late_aircraft_delay`) means a previous flight with the same aircraft arrived late which caused the present flight to depart late.


***

# Approaches

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; We selected 23 relevant variables and chose time ranges from 2012 Janurary to 2016 December. Our variables of interest fall into three categories based on variable types:`Indicator variables`, `Continuous variables`,`Categorical variables`. What's worth mentioning is that we only regard the flight arrival/departure time exceeding 15 minutes as delay in this project. Out of these variables, we have done statistical analyses on five main causes of delay - `Late Arriving Aircraft Delay(Minutes)`, `Security Delay(Minutes)`, `National Air System Delay(Minutes)`, `Weather Delay(Minutes)`, `Carrier Delay(Minutes)`. The statistical analyses were done
from different perspectives on delay frequency, time patterns, and hypothesis t test.




