---
title: "What are the main causes of delayed flights?"
output: html_document
---

<style type="text/css">

body{ /* Normal  */
      font-size: 16px;
  }
}
h1.title {
  font-size: 30px;
  color: DarkBlue;
}
h1 { /* Header 1 */
  font-size: 28px;
  color: DarkBlue;
}
h2 { /* Header 2 */
    font-size: 16px;
  color: DarkBlue;
}

}
code.r{ /* Code block */
    font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 14px;
}
</style>


\

 **5 major** causes:
        
  * Carrier delay
  * Weather delay 
  * National System delay 
  * Security delay 
  * Late aircraft delay 

\

 **31 combinations** of the major causes of flight delay

  * _TOP 1_: National Aviation System delay
  * _TOP 2_: Carrier delay & Late aircraft delay
  * _TOP 3_: Carrier delay 
  * _TOP 4_: Carrier delay & National Aviation System delay
  * _TOP 5_: National Aviation System delay & Late aircraft delay


***

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Our result parallels with the article, ‘An Answer to Flight Delays?’ by Tracy Samantha. A significant reason for flight delays breakdowns within the National Aviation System (NAS), which includes airports and the air traffic control centers. National Aviation System delay includes Flow control program, Volume Delays, Airport conditions, Bird strikes, _etc_. Since the NAS delay includes issues of a number of significant and complex factors, when the issues happened, many flights will be affected and might have a delay.\

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Also, Carrier delay and Late aircraft delay are major on the delayed flights. Carrier delay includes aircraft cleaning, awaiting gate space, engineering inspection, late minute passenger, removal of unruly passengers, _etc_. To avoid these effects, all airport staffs, crews, and passengers have the responsibility. Late aircraft delay is caused by the same aircraft arrived late which caused the current flight to depart late. The late aircraft delay might also cause more than one delayed flight since the delay might cumulative on the future flights.

***

Causes of Delay                                    | Counts
---------------------------------------------------|--------------
NAS                                                | 1,012,454
Carrier and Late aircraft                          | 910,725
Late aircraft                                      | 747,498	  
Carrier                                            | 727,226
Carrier, and NAS                                   | 649,942
NAS and Late aircraft                              | 608,158
Carrier, NAS, and Late aircraft                    | 573,158
Weather, and NAS                                   | 86,566
Weather, and Late aircraft                         | 70,939
Weather, NAS, and Late aircraft                    | 70,321
Weather                                            | 53,498
Carrier, Weather, NAS, and Late aircraft           | 7,783
NAS, and Security                                  | 5,668
Carrier, Weather, and NAS                          | 5,625
Carrier, Weather, and Late aircraft                | 5,429
Carrier and Weather                                | 5,428
Secuirty and Late aircraft                         | 4,456
Secuity                                            | 3,562
NAS, Security, and Late aircraft                   | 2,792
Carrier and Security                               | 570
Carrier, NAS, and Security                         | 360
Carrier, Security, and Late aircraft               | 205
Carrier, NAS, Security, and Late aircraft          | 155
Weather and Security                               | 76
Weather, NAS, and Security                         | 15
Carrier, Weather, and Security                     | 12
Weather, Security, and Late aircraft               | 12
Carrier, Weather, Security, Late aircraft          | 5
Carrier, Weather, NAS, Security, and Late aircraft | 1
Carrier, Weather,NAS, Security                     | 1
Weather, NAS, Security, and Late aircraft          | 1



